namespace PDFEditor.Core
{
    [default_interface]
    runtimeclass Application
    {
        Application();

        static Application GetDefault();
        Void Initialize();
        Void Shutdown();
        Boolean IsInitialized{ get; };
    }
}
