namespace PDFEditor.Core
{
    [default_interface]
    runtimeclass CommandManager
    {
        CommandManager();

        Void ExecuteCommand(String name, String parameters);
        Boolean Undo();
        Boolean Redo();

        Boolean CanUndo{ get; };
        Boolean CanRedo{ get; };
        UInt32 UndoDepth{ get; set; };

        Void Clear();
        Void BeginMacro(String name);
        Void EndMacro();
    }
}
